### ISSUE TITLE
Demo for fkooman/php-oauth-as?

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth.net#101]
@fkooman I just noticed your server is linked from http://oauth.net/2/ and points to a demo URL that no longer works. Do you have that running at a new location? See https://github.com/aaronpk/oauth.net/blob/master/2/index.php#L49

**Comment by fkooman** [comment]
Hi, there currently is no demo available anywhere unfortunately. So the demo link can be removed :)
