### ISSUE TITLE
Would like to post a middleware project to the website

### ISSUE THREAD

**Issue by LappleApple** [aaronpk/oauth.net#117]
Hi there--am wondering if it's okay to create a new section for middleware and add [my colleagues' Gin project](https://github.com/zalando-techmonkeys/gin-oauth2). As noted in the README, "Gin-OAuth2 is specially made for Gin Framework users who also want to use OAuth2. It was created by Go developers who needed Gin middleware for working with OAuth2 and couldn't find any." Thanks!

**Comment by aaronpk** [comment]
Do you know of any other middleware libraries that could be added to the list? I'd be okay with adding the section if there will be more than one item in it.

**Comment by aaronpk** [comment]
Feel free to submit a PR that adds this to the Server Libraries section of the "Code" page. https://oauth.net/code/

**Comment by LappleApple** [comment]
Hi -- for some reason I didn't see your May 11 comment, only this most recent one. I'll add now. Thanks!
