### ISSUE TITLE
Golang Oauth2 Server framework

### ISSUE THREAD

**Issue by LyricTian** [aaronpk/oauth.net#131]
Should this [https://github.com/go-oauth2/oauth2](https://github.com/go-oauth2/oauth2) be include?

**Comment by aaronpk** [comment]
Sure! Feel free to send a PR!

**Comment by LyricTian** [comment]
Has been sent,[https://github.com/aaronpk/oauth.net/pull/132](https://github.com/aaronpk/oauth.net/pull/132)

**Comment by aaronpk** [comment]
Thanks!
