### ISSUE TITLE
OAuth Unsuccessful Response

### ISSUE THREAD

**Issue by sm2017** [aaronpk/oauth.net#198]
According to https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/

> Error responses are returned with an HTTP 400 status code (unless
> specified otherwise), with error and error_description parameters. The
> error parameter will always be one of the values listed below.
> 
> * invalid_request
> * invalid_client
> * invalid_grant
> * invalid_scope
> * unauthorized_client
> * unsupported_grant_type

Can I have custom error like "invalid_captcha" or "captcha_required"?

I want , if some one send wrong credentials for 3 times , I send "captcha_required" error and for next time must send valid captcha code

My question is:

1. Is it allowed to define custom error codes in OAuth ?
2. Is there alternative way to solve my problem?

**Comment by aaronpk** [comment]
Hi, thanks for your question! This isn't the best place to ask questions about the spec itself, this repo is just for the website.

This sounds like an excellent question for the mailing list. It's quick to join, and then you can post your question there which should get picked up by a larger audience of people with a wide variety of implementation experience.

https://www.ietf.org/mailman/listinfo/oauth
