### ISSUE TITLE
How to get listed in : https://oauth.net/code/ page ?

### ISSUE THREAD

**Issue by vimalprakashts** [aaronpk/oauth.net#210]
hi @AArnott , I developed a Oauth2 and OpenId connect system, I Like to listed in https://oauth.net/code/  page. what is the procedure for that?

**Comment by AArnott** [comment]
No idea. I realize my library is listed, but I haven't worked on it in years and it looks like that site has changed significantly since I was added to the list.

**Comment by vimalprakashts** [comment]
any one knows how to get listed here ?

**Comment by aaronpk** [comment]
You can send a pull request to that page with the changes
