### ISSUE TITLE
Deprecation of Password Grant flow leaves a gap in authenticating a client as its own user

### ISSUE THREAD

**Issue by jonjrwhite** [aaronpk/oauth.net#239]
I believe that the deprecation of the Password Grant flow leaves a gap in situations where a third-party client needs to authenticate with an API with a specific user account which is different to the user account of the end user on the client.

The primary reason for the deprecation of Password Grant is that the users' credentials are exposed to the client. However, where the end user is authenticated with the client application as a user internal to the client and the client authenticates as a user within the scope of the API using it's own credentials, there is no issue with the credentials being handled by the client.
In this situation the recommended Auth Code flow is not appropriate because it requires the logged in user to consent to the authentication which requires a manual interaction in the browser.
In the case of the Password Grant flow, the client can authenticate with the API without manual interaction.

Assuming the client is a server-side application with the credentials obscured from the end user, I see no reason why Password Grant is not appropriate. Otherwise, what is the appropriate alternative that enables a client to automatically authenticate with a client without user interaction but scoped to a particular user account?

**Comment by aaronpk** [comment]
This isn't really the place for questions like this, this repo is just for the oauth.net website, not for discussing spec issues. That said, what you're describing of "a user internal to the client" sounds like an overloading of the password grant in the first place. You're probably better off using the Client Credentials grant since there isn't really an end user in this flow at all.

**Comment by jonjrwhite** [comment]
@aaronpk thanks for your response. I see now that this repo is more for the website and therefore not the appropriate place for the question.

However, you answer has been very helpful and I'm now a littler clearer on the fact the the spec deals more with the concept of the `end` user. So in that sense the Client Credentials grant is appropriate for authenticating a client as a user within the context of the API but not where a single Client ID may enable multiple users to log in as was the case with the password grant.
