### ISSUE TITLE
oauth.com errata?

### ISSUE THREAD

**Issue by somebody1234** [aaronpk/oauth.net#256]
minor nitpicks for this page: <https://www.oauth.com/oauth2-servers/access-tokens/self-encoded-access-tokens/>
i'm aware this isn't the repo for oauth.com (not that it even has a repo) but anyway.

- smart quote in header json obj: `"HS256”`, and
- `sub` is a registered claim name with type `StringOrURI`, so don't think a number belongs there

**Comment by aaronpk** [comment]
Thank you, this has been fixed.
