### ISSUE TITLE
Regarding Oauth authentication, the request URL contains the security issue of redirect_uri

### ISSUE THREAD

**Issue by ximiluliyi** [aaronpk/oauth.net#263]
Hello, technical engineers, I would like to consult about the Oauth certification process. The redirect_uri request parameter in the certification URL will trigger the security product rules and cause the request to be intercepted. The triggered security rule is: "Server-Side Request Forgery", for details The parameter is caused by redirect_uri, is there any solution? For example, can the parameter redirect_uri in the URL be changed to another name, because the security product recognizes that the normal request caused by the redirect_uri is intercepted, and the attached image is the detailed data packet that was intercepted when the request was initiated. If you can reply, I am very grateful.
![image](https://user-images.githubusercontent.com/40221289/122670086-a7a79280-d1f2-11eb-94f2-a15f86123e88.png)

**Comment by aaronpk** [comment]
This would be a better question for the mailing list. This repository is just for the website oauth.net.

https://mailarchive.ietf.org/arch/browse/oauth/
