### ISSUE TITLE
Powershell file is missing

### ISSUE THREAD

**Issue by adrwh** [aaronpk/oauth.net#270]

**Comment by aaronpk** [comment]
What powershell file?

**Comment by adrwh** [comment]
Sorry that was an un helpful comment, I was on mobile and rushed. 

You link to a powershell oauth  client here https://github.com/GlobalSign/OAuth-2.0-client-examples/blob/master/PowerShell/Powershell-example.ps1

**Comment by aaronpk** [comment]
thanks, looks like they deleted the whole repo!
