### ISSUE TITLE
Link to OAuth 2.1 draft is broken

### ISSUE THREAD

**Issue by JuliusPC** [aaronpk/oauth.net#273]
The link to OAuth 2.1 spec on [Specs page](https://oauth.net/specs/) is broken. <https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1> results in a 404. As the same formatted [link to the security BCP](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics) works, I suspect this may be a bug on the IETF’s site – maybe their page interprets the `-1` as version identifier?

Another thing I noticed: The pages title is "Code". A copy ’n’ paste error?

BTW: Thanks for maintaining oauth.net!

**Comment by aaronpk** [comment]
Yeah this is a bug in a recent change they pushed out to the datatracker URLs, it's being tracked here: https://trac.ietf.org/trac/ietfdb/ticket/3417

I don't see any traffic on that ticket so I should work around it in the mean time.

**Comment by Stanleystarsly** [comment]
EIPGC2GPXA5PBQ7PB57A

https://www.eventbriteapi.com/v3/users/me/?

token=EIPGC2GPXA5PBQ7PB57A

EIPGC2GPXA5PBQ7PB57A

**Comment by aaronpk** [comment]
I updated the links to work around the bug. They have been attempting to fix it as well.
