### ISSUE TITLE
Authorization Code Grant speaks about "this flow"

### ISSUE THREAD

**Issue by spaceone** [aaronpk/oauth.net#341]
https://oauth.net/2/grant-types/authorization-code/ is the Authorization Code **Grant**, not a specific **Flow**.
But it says:

> It is recommended that all clients use the [PKCE](https://oauth.net/2/pkce/) extension with this flow as well to provide better security.

This information also isn't true? If you have a private client where the client secret is only known to the resource server having PKCE doesn't make sense?!

**Comment by aaronpk** [comment]
Please read the page on PKCE linked from that paragraph for details about why a client with a secret also needs to use PKCE.

https://oauth.net/2/pkce/

"Flow" refers to the end to end process. "Grant" refers to the specific step of exchanging the authorization code.
