### ISSUE TITLE
According to the RFC, must the client Identifier be "client_id"  ?

### ISSUE THREAD

**Issue by ipv4sec** [aaronpk/oauth.net#356]
when i read this docs: https://developer.open-douyin.com/docs/resource/zh-CN/dop/develop/openapi/account-permission/get-access-token , client Identifier is "client_key", Is this correct ？Thanks

**Comment by aaronpk** [comment]
`client_id` is the name of the OAuth 2 parameter for this, not `client_key`. In OAuth 1 there was `consumer_key` so it's possible someone confused it with that.
