### ISSUE TITLE
ScalaOAuth

### ISSUE THREAD

**Issue by mfirry** [aaronpk/oauth.net#51]
Should this http://www.playframework.com/documentation/2.0/ScalaOAuth be included?

**Comment by aaronpk** [comment]
It looks like it's an OAuth 1 library so I added it to http://oauth.net/code/

**Comment by mfirry** [comment]
While you're at it, Play is now at version 2.5. So current link should be https://www.playframework.com/documentation/2.5.x/ScalaOAuth

Thanks
